### ISSUE TITLE
New update removed ability to view db of a specific frequency.

### ISSUE THREAD

**Issue by CyberLykan** [mlochbaum/CrinGraph#2]
Normalizing the graph at the frequency would give you the offset from flat. Ever since the normalize by db feature was added, this doesn't work anymore.

Example: Flat is 60db. Normalizing at 1000hz brings the graph down -5.4321, which means that frequency's db level is 65.4321

**Comment by mlochbaum** [comment]
I'm thinking about how to make a good interface for this. It would help to know what you've been using it for. Note that if you just want a little more precision you can widen the scaler at the left and you'll get grid lines every 2dB. I'll change that to keep the 5dB lines and add thin 1dB ones some day.

Right now I'm thinking there could be a switch in the bottom bar to turn on dB annotations. Once you do that you would get a display on mouseover (or click/touch) to show values for each graph.

The update removes any concept of an actual or original level for the measurements: it all depends on the current normalization (you're not losing anything: the "original" curves are normalized, but badly). So you'd only be able to see where points are on the graph currently.

**Comment by CyberLykan** [comment]
I have been using this trick to get a more accurate EQ for my earbuds. It's a lot better than taking a screenshot, throwing it into Photoshop, and finding the db level by distance.

As for the interface, that's a good idea.

**Comment by mlochbaum** [comment]
This now works on the [demo page](https://mlochbaum.github.io/CrinGraph/graph.html) and will be on Crin's site when he updates it next. Just hit "dB on mouseover" and you're good to go.
