### ISSUE TITLE
wish add a function which can paint the THD graph

### ISSUE THREAD

**Issue by SensmD** [mlochbaum/CrinGraph#22]
Just like the title saying. Thanks you very much if the software can update this function.

**Comment by mlochbaum** [comment]
This is a much larger feature than I'm willing to take on now. Adding a new kind of measurement affects just about every part of the program from loading to display to interaction, and would require a fair amount of interface design for basic usability features like being able to rescale or hide the THD graph. I'm very busy with other projects and am only doing simple maintenance here.

**Comment by SensmD** [comment]
Okay, so I will try to develop this feature, and so far I think the tool is very powerful than I think, and I am very appreciate it that you reply me soon. nice job, because it helps me a lot.
